import numpy as np
import time
print("=================================punto1===========================================================")
vector1 = np.array([1,2,3,4,5])
print(vector1)
for x in vector1:
    print(x)
time.sleep(1.5)
print("=================================punto2===========================================================")
vector2 = np.array([5,4,3,2,1])
for x in range(len(vector1)):
    print(vector1[x]+vector2[x])
time.sleep(1.5)
print("=================================punto3===========================================================")
vector3 = np.array([4,2,56,6,7])
vector4 = np.array([7,8,3,1,6])
print(f"El producto x 2 del vector 1 es {vector3*2} \nY del vector 2 es {vector4*2}")
time.sleep(1.5)
print("=================================punto4===========================================================")
vector5 = np.array([7,8,3,1,6])
numero = int(input("Ingrese un numero para multiplicar el vector: "))
print(f"El producto del vector es {(vector5*numero)}")
time.sleep(1.5)
print("=================================punto5===========================================================")
vector6 = np.array([7,28,3,1,6])
print(f"El promedio del vector es: {np.mean(vector6)}")
time.sleep(1.5)
print("=================================punto6===========================================================")
vector7 = np.array([4,5,3,5,6])
indice = int(input(f"Ingrese un valor entre 0 y {len(vector7)-1}: "))
print(f"El indice {indice} del vector tiene el valor: {vector7[indice]}")